#!/usr/bin/env bash
# Rename teamem to flopwire across the tracked tree. Idempotent: a second
# run changes nothing.
#
# To move a branch that predates the rename onto main:
#   1. On the branch, run scripts/rename-flopwire.sh and commit the result.
#   2. Rebase onto main. Conflicts that remain are the branch's own changes.
#   3. Run `make web` if the branch touched web/.
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

# Paths first, so content edits land in the renamed files.
git ls-files -z | tr '\0' '\n' | { grep -i teamem || true; } | while IFS= read -r old; do
	new=$(printf '%s' "$old" | sed -e 's/dev\.teamem\.agent/com.flopwire.agent/g' \
		-e 's/TEAMEM/FLOPWIRE/g' -e 's/Teamem/Flopwire/g' -e 's/teamem/flopwire/g')
	mkdir -p "$(dirname "$new")"
	git mv "$old" "$new"
done

# Content. The built web bundle is regenerated by `make web`, not edited.
{ git grep -I -l -i -z teamem -- . ':!scripts/rename-flopwire.sh' ':!internal/webapp/dist' || true; } |
	xargs -0 -r perl -pi -e '
		s{github\.com/teamem/teamem}{github.com/flopwire/flopwire}g;
		s{github\.com/gbasin/teamem}{github.com/flopwire/flopwire}g;
		s{dev\.teamem\.agent}{com.flopwire.agent}g;
		s{TEAMEM}{FLOPWIRE}g;
		s{Teamem}{Flopwire}g;
		s{teamem}{flopwire}g;
	'

# The redaction fixture splits the token prefix so the literal never appears
# in source; keep it split.
perl -pi -e 's{"tea" \+ "mem_"}{"flop" + "wire_"}g' internal/redact/redacttest/planted.go

# The new module path sorts differently among imports.
git ls-files -z '*.go' ':!third_party' | xargs -0 -r gofmt -w
