package main

import (
	"fmt"
	"html"
	"strings"

	"github.com/flopwire/flopwire/internal/busproto"
)

// Delivery status is generated by the bus, without peer text or reply
// instructions. It is deliberately distinct from flopwire-message, so it
// cannot forge a peer or create a read receipt.
func deliveryStatus(in []busproto.DeliveryFailure) string {
	if len(in) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("\n<flopwire-delivery-status>\nSystem delivery status:\n")
	for _, n := range in {
		reason := n.Reason
		switch reason {
		case "session_ended", "expired", "push_failed", "unconfirmed":
		default:
			reason = "delivery_failed"
		}
		fmt.Fprintf(&b, "Message %s delivery status: %s.", html.EscapeString(n.ID), reason)
		if n.Attempt > 1 {
			b.WriteString(" Status redelivery: an earlier print was not acknowledged.")
		}
		b.WriteByte('\n')
	}
	b.WriteString("</flopwire-delivery-status>\n")
	return b.String()
}
