// Package synthcorpus generates a deterministic synthetic harness corpus
// (Claude Code projects, Codex rollouts, a Devin sessions.db) shaped like
// the reference corpus of notes/local-search/README.md §2.1, at a size a
// hosted CI runner can index. It also writes a query set whose expected
// hits are known by construction (needles planted in chosen messages).
//
// Everything is synthetic: no real transcript content is read or copied.
// The same Config always yields byte-identical files.
package synthcorpus

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"slices"
	"sync"
	"time"
)

// Version changes whenever the generated bytes change for a given Config.
// CI caches the corpus under it.
const Version = 1

// Reference shape (notes/local-search/README.md §2.1), scaled by Config.Bytes.
const (
	codexFileShare  = 0.51  // of non-Devin files
	subagentShare   = 0.57  // of Claude files
	bigByteShare    = 0.30  // bytes in files over the big threshold (5.4GB of 18.2GB)
	devinByteShare  = 0.005 // the Devin store
	defaultBigMin   = 21 << 20
	windowStartUnix = 1782864000 // 2026-07-01T00:00:00Z
	windowDays      = 89         // to 2026-09-28
)

// Config selects the corpus.
type Config struct {
	Seed  uint64
	Bytes int64 // target transcript bytes, all agents
	// BigMin is the size above which a file counts as big (default 21MB);
	// tests lower it to get big files in a small corpus.
	BigMin int64
}

// Layout of a corpus root (a fake $HOME).
func ClaudeProjects(root string) string { return filepath.Join(root, ".claude", "projects") }
func CodexHome(root string) string      { return filepath.Join(root, ".codex") }
func DevinDB(root string) string {
	return filepath.Join(root, ".local", "share", "devin", "cli", "sessions.db")
}
func QueriesPath(root string) string  { return filepath.Join(root, "queries.yaml") }
func ManifestPath(root string) string { return filepath.Join(root, "manifest.json") }

// Manifest describes a generated corpus. It is written to ManifestPath.
type Manifest struct {
	Version     int    `json:"version"`
	Seed        uint64 `json:"seed"`
	TargetBytes int64  `json:"target_bytes"`
	BigMin      int64  `json:"big_min"`

	Files       int     `json:"files"` // transcript files (JSONL) plus the Devin store
	Bytes       int64   `json:"bytes"`
	ClaudeFiles int     `json:"claude_files"` // main transcripts
	Subagents   int     `json:"claude_subagents"`
	Companions  int     `json:"claude_tool_results"`
	ClaudeBytes int64   `json:"claude_bytes"`
	CodexFiles  int     `json:"codex_files"`
	CodexBytes  int64   `json:"codex_bytes"`
	DevinBytes  int64   `json:"devin_bytes"`
	DevinSess   int     `json:"devin_sessions"`
	BigFiles    int     `json:"big_files"`
	BigBytes    int64   `json:"big_bytes"`
	LargestFile int64   `json:"largest_file"`
	Lines       int64   `json:"lines"`
	LineP50     int     `json:"line_p50"`
	LineP99     int     `json:"line_p99"`
	LineMax     int     `json:"line_max"`
	HugeShare   float64 `json:"bytes_in_lines_over_100kb"`

	// Needles maps each needle to how many messages carry it.
	Needles map[string]int `json:"needles"`
}

type agentKind int

const (
	agentClaude agentKind = iota
	agentCodex
)

// fileSpec is one planned transcript file.
type fileSpec struct {
	idx   int
	agent agentKind
	id    string // session id
	cwd   string
	start time.Time
	gap   time.Duration
	size  int64
	path  string

	// Claude main sessions: subagent files it spawns.
	subs []*fileSpec
	// Claude subagents: the parent session and spawn tool_use id.
	parent    *fileSpec
	agentID   string
	toolUseID string

	plants []plant
}

func (f *fileSpec) isSub() bool { return f.parent != nil }

// plant puts needle text into one message: prose (user or assistant text)
// or, for Claude, a tool output. at is the fraction of the file after
// which it is written.
type plant struct {
	text   string
	needle string
	tool   bool
	at     float64
}

var repos = []string{"harbor", "ledger", "kernel", "atlas", "beacon", "canopy", "delta", "ember", "fable", "grove", "helix", "ivory"}

func cwdOf(repo string) string { return "/workspace/" + repo }

// Generate writes the corpus under root, which must be empty or absent,
// and returns its manifest.
func Generate(root string, cfg Config) (*Manifest, error) {
	if cfg.BigMin <= 0 {
		cfg.BigMin = defaultBigMin
	}
	if cfg.Bytes < 1<<20 {
		return nil, fmt.Errorf("synthcorpus: target %d bytes is below 1MiB", cfg.Bytes)
	}
	if ents, err := os.ReadDir(root); err == nil && len(ents) > 0 {
		return nil, fmt.Errorf("synthcorpus: %s is not empty", root)
	}
	p := newPlan(cfg)
	qs := p.plantQueries()

	for _, f := range p.files {
		f.path = p.pathOf(root, f)
	}
	// Write files in parallel; each has its own random stream.
	results := make([]fileResult, len(p.files))
	var wg sync.WaitGroup
	jobs := make(chan int)
	errs := make([]error, len(p.files))
	for range runtime.NumCPU() {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for i := range jobs {
				results[i], errs[i] = writeFile(cfg.Seed, p.files[i], root)
			}
		}()
	}
	var devinRes fileResult
	var devinErr error
	wg.Add(1)
	go func() {
		defer wg.Done()
		devinRes, devinErr = writeDevin(cfg.Seed, DevinDB(root), p.devin)
	}()
	for i := range p.files {
		jobs <- i
	}
	close(jobs)
	wg.Wait()
	if err := devinErr; err != nil {
		return nil, err
	}
	for _, err := range errs {
		if err != nil {
			return nil, err
		}
	}

	m := &Manifest{Version: Version, Seed: cfg.Seed, TargetBytes: cfg.Bytes, BigMin: cfg.BigMin, Needles: map[string]int{}}
	var lineSizes []int
	var huge int64
	for i, f := range p.files {
		r := results[i]
		m.Files++
		m.Bytes += r.bytes
		m.Companions += r.companions
		m.Lines += int64(len(r.lineSizes))
		lineSizes = append(lineSizes, r.lineSizes...)
		huge += r.hugeBytes
		m.LargestFile = max(m.LargestFile, r.bytes)
		if r.bytes >= cfg.BigMin {
			m.BigFiles++
			m.BigBytes += r.bytes
		}
		switch {
		case f.agent == agentCodex:
			m.CodexFiles++
			m.CodexBytes += r.bytes
		case f.isSub():
			m.Subagents++
			m.ClaudeBytes += r.bytes
		default:
			m.ClaudeFiles++
			m.ClaudeBytes += r.bytes
		}
		for n, c := range r.planted {
			m.Needles[n] += c
		}
	}
	m.Files++
	m.Bytes += devinRes.bytes
	m.DevinBytes = devinRes.bytes
	m.DevinSess = len(p.devin)
	for n, c := range devinRes.planted {
		m.Needles[n] += c
	}
	slices.Sort(lineSizes)
	if len(lineSizes) > 0 {
		m.LineP50 = lineSizes[len(lineSizes)/2]
		m.LineP99 = lineSizes[len(lineSizes)*99/100]
		m.LineMax = lineSizes[len(lineSizes)-1]
	}
	if m.Bytes > 0 {
		m.HugeShare = float64(huge) / float64(m.Bytes-m.DevinBytes)
	}
	for _, q := range qs {
		want := 0
		for _, n := range q.needles {
			want += m.Needles[n]
		}
		if want != q.planned {
			return nil, fmt.Errorf("synthcorpus: query %s: planted %d of %d needles", q.Name, want, q.planned)
		}
	}
	if err := writeQueries(QueriesPath(root), qs); err != nil {
		return nil, err
	}
	data, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		return nil, err
	}
	return m, os.WriteFile(ManifestPath(root), append(data, '\n'), 0o644)
}

// plan is the deterministic list of files and sessions.
type plan struct {
	cfg   Config
	r     rng
	files []*fileSpec // Claude mains, Claude subagents, Codex rollouts
	devin []*devinSession
}

func newPlan(cfg Config) *plan {
	p := &plan{cfg: cfg, r: newRNG(cfg.Seed, 0)}
	r := p.r
	devinBytes := max(256<<10, int64(float64(cfg.Bytes)*devinByteShare))
	rest := cfg.Bytes - devinBytes

	// Big files first: about 30% of the bytes, sizes log-uniform between
	// BigMin and a cap that keeps any single file under 1/12 of the corpus.
	bigBudget := int64(float64(rest) * bigByteShare)
	bigMax := max(float64(cfg.BigMin)*1.5, min(213<<20, float64(cfg.Bytes)/12))
	var bigs []int64
	for bigBudget >= cfg.BigMin {
		s := min(int64(r.logUniform(float64(cfg.BigMin), bigMax)), bigBudget)
		if s < cfg.BigMin {
			break
		}
		bigs = append(bigs, s)
		bigBudget -= s
	}
	for _, s := range bigs {
		rest -= s
		a := agentClaude
		if r.Float64() < 0.65 {
			a = agentCodex
		}
		p.add(a, s, false)
	}
	// The rest: many small and medium files, heavy-tailed.
	sizeCap := float64(cfg.BigMin - 1)
	clip := func(v float64) int64 { return int64(min(max(v, 4<<10), sizeCap)) }
	var lastMain *fileSpec
	for rest > 0 {
		var s int64
		var f *fileSpec
		switch u := r.Float64(); {
		case u < codexFileShare:
			s = clip(r.lognormal(350<<10, 1.8))
			f = p.add(agentCodex, min(s, rest), false)
		case lastMain == nil || u < codexFileShare+(1-codexFileShare)*(1-subagentShare):
			s = clip(r.lognormal(300<<10, 1.8))
			f = p.add(agentClaude, min(s, rest), false)
			lastMain = f
		default:
			s = clip(r.lognormal(50<<10, 1.5))
			f = p.add(agentClaude, min(s, rest), true)
			f.parent = lastMain
			f.id = lastMain.id
			f.cwd = lastMain.cwd
			f.agentID = hex(r.Uint64(), 16) + hex(r.Uint64(), 1)
			f.toolUseID = "toolu_" + hex(r.Uint64(), 16)
			f.start = lastMain.start.Add(time.Duration(len(lastMain.subs)+1) * time.Minute)
			lastMain.subs = append(lastMain.subs, f)
		}
		rest -= f.size
	}
	p.devin = planDevin(r, devinBytes)
	return p
}

func (p *plan) add(a agentKind, size int64, sub bool) *fileSpec {
	r := p.r
	f := &fileSpec{idx: len(p.files), agent: a, size: size}
	if !sub {
		if a == agentCodex {
			f.id = r.uuid7()
		} else {
			f.id = r.uuid4()
		}
		f.cwd = cwdOf(repos[r.IntN(len(repos))])
		f.start = time.Unix(windowStartUnix+r.Int64N(windowDays*86400-12*3600), 0).UTC()
	}
	// Spread the lines of a session over at most ~6 hours.
	est := max(1, size/2500)
	f.gap = min(20*time.Second, max(50*time.Millisecond, 6*time.Hour/time.Duration(est)))
	p.files = append(p.files, f)
	return f
}

func (p *plan) pathOf(root string, f *fileSpec) string {
	switch {
	case f.agent == agentCodex:
		t := f.start
		return filepath.Join(CodexHome(root), "sessions", t.Format("2006"), t.Format("01"), t.Format("02"),
			"rollout-"+t.Format("2006-01-02T15-04-05")+"-"+f.id+".jsonl")
	case f.isSub():
		return filepath.Join(ClaudeProjects(root), projectDir(f.cwd), f.id, "subagents", "agent-"+f.agentID+".jsonl")
	default:
		return filepath.Join(ClaudeProjects(root), projectDir(f.cwd), f.id+".jsonl")
	}
}

// projectDir encodes a cwd like Claude Code does ("/a/b" -> "-a-b").
func projectDir(cwd string) string {
	b := []byte(cwd)
	for i, c := range b {
		if c == '/' || c == '.' {
			b[i] = '-'
		}
	}
	return string(b)
}

// fileResult is what writing one file produced.
type fileResult struct {
	bytes      int64
	companions int
	lineSizes  []int
	hugeBytes  int64 // bytes in lines over 100KB
	planted    map[string]int
}
